// English translations of data.js (keyed by id, or by the Chinese name when there is no id).
// Chinese names stay in data.js so the app can always show them to locals, taxi drivers and vendors.

export const REGION_EN = { 北部: 'North', 中部: 'Central', 南部: 'South', 東部: 'East', 離島: 'Islands' };

export const INTEREST_EN = {
  自然: 'Nature', 文化: 'Culture & history', 老街: 'Old streets', 美食: 'Night markets & food', 溫泉: 'Hot springs',
  親子: 'Family-friendly', 購物: 'Shopping', 拍照: 'Photo spots', 海邊: 'Beaches & islands', 登山: 'Hiking',
  夜景: 'Night views', 室內: 'Rainy-day indoor',
};

export const FOOD_TYPE_EN = {
  小吃: 'Street food', 夜市: 'Night market', 甜點: 'Dessert', 飲品: 'Drinks', 伴手禮: 'Souvenir',
  餐廳: 'Restaurant', 水果: 'Fruit', 早餐: 'Breakfast',
};

export const DEST_EN = {
  taipei: { name: 'Taipei', intro: 'The capital mixes modern city life with old temples. The MRT goes almost everywhere, and it has the highest density of street food and night markets in Taiwan.', localTransport: 'MRT + buses are easiest. An EasyCard works on the MRT, buses and YouBike bikes.' },
  jiufen: { name: 'Jiufen', intro: 'A hillside gold-mining town of red lanterns, stone steps and sea views.', localTransport: 'Walk the old street. Buses 788 and 1062 go on to Jinguashi.' },
  tamsui: { name: 'Tamsui', intro: 'A riverside town with an old street, colonial forts and famous sunsets.', localTransport: 'Walk from MRT Tamsui station. Buses or a ferry go to Fisherman’s Wharf.' },
  pingxi: { name: 'Pingxi', intro: 'Railway villages where you release sky lanterns right on the train tracks.', localTransport: 'Ride the Pingxi branch line between Shifen, Pingxi and Jingtong; a one-day pass is sold at stations.' },
  keelung: { name: 'Keelung', intro: 'A rainy harbour city famous for its temple night market.', localTransport: 'City buses; Heping Island and Zhengbin port are 15–20 minutes from the centre.' },
  yilan: { name: 'Yilan', intro: 'Just through the Snow Mountain tunnel: hot springs, rice fields and traditional arts.', localTransport: 'Trains link Jiaoxi, Yilan and Luodong. Tourist Shuttle buses or a rental car reach the sights.' },
  taoyuan: { name: 'Taoyuan', intro: 'Home of the international airport, with the Daxi old street and a big aquarium.', localTransport: 'HSR Taoyuan station connects to the Airport MRT. Take a bus or taxi to Daxi.' },
  airport: { name: 'Taoyuan Airport', intro: 'Taiwan’s main international gateway. Take the Airport MRT into Taipei or change to the HSR.', localTransport: 'The Airport MRT express reaches Taipei Main Station in about 35–40 minutes.' },
  hsinchu: { name: 'Hsinchu', intro: 'The “windy city”: temple street food and the Hakka mountain town of Neiwan.', localTransport: 'HSR Hsinchu station is in Zhubei; the Liujia train line goes into the city.' },
  taichung: { name: 'Taichung', intro: 'A sunny, relaxed city with big night markets, creative spaces and a claim to inventing bubble tea.', localTransport: 'HSR Taichung is in Wuri; take the train, MRT Green Line or a bus into the city (15–30 min).' },
  sunmoonlake: { name: 'Sun Moon Lake', intro: 'Taiwan’s largest natural lake, surrounded by mountains; lovely in every season.', localTransport: 'Get around the lake by boat, the lake bus or bicycle. A cable car goes to the Formosan Aboriginal Culture Village.' },
  chiayi: { name: 'Chiayi', intro: 'Gateway to Alishan and the home of turkey rice.', localTransport: 'HSR Chiayi is in Taibao; take the BRT into town (about 30 min).' },
  alishan: { name: 'Alishan', intro: 'Sunrise, sea of clouds, a forest railway and giant trees: Taiwan’s best-known mountain area.', localTransport: 'Inside the park, walk or ride the forest railway branch lines (Zhushan, Shenmu).' },
  tainan: { name: 'Tainan', intro: 'Taiwan’s oldest city, packed with historic sites, and widely seen as the capital of street food.', localTransport: 'From HSR Tainan take the Shalun line to Tainan station. In town, use YouBike, a scooter or a taxi.' },
  kaohsiung: { name: 'Kaohsiung', intro: 'A sunny port city with art districts, harbour views and temples.', localTransport: 'HSR Zuoying links to the Kaohsiung MRT; a light rail loops the harbour, and ferries go to Cijin.' },
  kenting: { name: 'Kenting', intro: 'Taiwan’s tropical southern tip and a marine national park, warm all year.', localTransport: 'Kenting shuttle buses run but are infrequent; most visitors rent a scooter or e-bike.' },
  hualien: { name: 'Hualien', intro: 'Between the Pacific and the Central Mountains on the east coast.', localTransport: 'The city is small enough for YouBike. For sights outside town, hire a driver, rent a car or take the Tourist Shuttle.' },
  taroko: { name: 'Taroko', intro: 'A world-famous marble gorge.', localTransport: 'Take the Taiwan Tourist Shuttle Taroko route or hire a driver.' },
  taitung: { name: 'Taitung', intro: 'Laid-back east coast: rice fields, hot-air balloons and hot springs.', localTransport: 'Sights are spread out; rent a car or join a day tour. Bikes can be rented in Chishang.' },
  penghu: { name: 'Penghu', intro: 'Islands of basalt cliffs and clear water, famous for summer fireworks.', localTransport: 'Rent a scooter or join a day tour on the main islands; island-hopping needs a boat.' },
};

export const ATTR_EN = {
  tp101: { name: 'Taipei 101', desc: 'Taipei’s landmark tower; the 89th-floor observatory looks over the whole city.', tip: 'Go up just before sunset to see both the sunset and the night view.' },
  npm: { name: 'National Palace Museum', desc: 'Hundreds of thousands of Chinese artefacts, including the famous Jadeite Cabbage.', tip: 'Go in the morning to avoid tour groups; rent the audio guide.' },
  cks: { name: 'Chiang Kai-shek Memorial Hall', desc: 'White memorial hall with a blue roof and a huge square; guard change on the hour.' },
  xiangshan: { name: 'Elephant Mountain Trail', desc: 'A 20–30 minute climb to the classic Taipei 101 viewpoint.', tip: 'Start about 40 minutes before sunset.' },
  ximen: { name: 'Ximending', desc: 'Taipei’s youth and fashion district, full of cinemas, shops and snacks.' },
  dadaocheng: { name: 'Dadaocheng & Dihua Street', desc: 'Century-old shophouses, dried-goods stores and the Xiahai City God Temple; riverside sunsets nearby.' },
  beitou: { name: 'Beitou Hot Springs', desc: 'A hot-spring town on the MRT; Thermal Valley and the Hot Spring Museum are free.' },
  yangming: { name: 'Yangmingshan National Park', desc: 'Volcanic landscapes, calla lilies in spring and silver grass in autumn.', tip: 'Mountain weather changes fast; bring a jacket and rain gear.' },
  huashan: { name: 'Huashan 1914 Creative Park', desc: 'A former winery turned creative park with exhibitions and markets.' },
  'jiufen-st': { name: 'Jiufen Old Street', desc: 'Red lanterns and teahouses along Shuqi Road are the classic view.', tip: 'Prettiest when the lanterns light up at dusk; very crowded on weekends, so go on a weekday.' },
  'gold-museum': { name: 'Gold Museum (Jinguashi)', desc: 'Touch a 220 kg gold bar and explore old Japanese-era houses.' },
  teapot: { name: 'Teapot Mountain Trail', desc: 'Views over the Yin-Yang Sea and the old smelter ruins.' },
  'tamsui-st': { name: 'Tamsui Old Street', desc: 'Riverside promenade lined with local snacks.' },
  fort: { name: 'Fort San Domingo', desc: 'Built by the Spanish in the 17th century, later the British consulate.' },
  fisherman: { name: 'Fisherman’s Wharf & Lover’s Bridge', desc: 'One of the best sunset spots near Taipei.' },
  shifen: { name: 'Shifen Old Street (sky lanterns)', desc: 'Write a wish on a lantern and release it as the train rolls past.' },
  'shifen-falls': { name: 'Shifen Waterfall', desc: 'Nicknamed the “Niagara of Taiwan”.' },
  jingtong: { name: 'Jingtong Station', desc: 'A wooden Japanese-era station and a street hung with wishing bamboo tubes.' },
  miaokou: { name: 'Keelung Miaokou Night Market', desc: 'A century-old night market around Dianji Temple, lit by rows of yellow lanterns.' },
  heping: { name: 'Heping Island Geopark', desc: 'Strange sea-eroded rocks and a seawater swimming pool.' },
  zhengbin: { name: 'Zhengbin Port Colour Houses', desc: 'Brightly painted houses reflected in the harbour.' },
  jiaoxi: { name: 'Jiaoxi Hot Springs', desc: 'Flat-land hot springs with a free foot bath next to the station.' },
  ncfta: { name: 'National Center for Traditional Arts', desc: 'Old-style streets, traditional crafts and opera performances.' },
  lanyang: { name: 'Lanyang Museum', desc: 'A striking tilted building about Yilan’s mountains and sea.' },
  luodong: { name: 'Luodong Night Market', desc: 'Yilan’s busiest night market.' },
  daxi: { name: 'Daxi Old Street', desc: 'Baroque-style shopfronts, famous for braised tofu.' },
  xpark: { name: 'Xpark Aquarium', desc: 'A modern aquarium right next to HSR Taoyuan station.' },
  chenghuang: { name: 'Hsinchu City God Temple', desc: 'A busy old temple surrounded by street-food stalls.' },
  neiwan: { name: 'Neiwan Old Street', desc: 'A Hakka mountain town at the end of the Neiwan train line.' },
  nanliao: { name: 'Nanliao Fishing Harbor', desc: 'Sea breeze, kites and a coastal bike path.' },
  gaomei: { name: 'Gaomei Wetlands', desc: 'Wind turbines and sunset reflections: Taichung’s best evening view.', tip: 'Check the tide and sunset times before you go.' },
  opera: { name: 'National Taichung Theater', desc: 'Toyo Ito’s building of flowing curved walls.' },
  fengjia: { name: 'Fengjia Night Market', desc: 'One of Taiwan’s largest night markets, always inventing new snacks.' },
  miyahara: { name: 'Miyahara & Shenji New Village', desc: 'A Japanese-era eye clinic turned dessert shop, plus a creative village.' },
  nmns: { name: 'National Museum of Natural Science', desc: 'Dinosaur halls and a space theatre; great with kids.' },
  rainbow: { name: 'Rainbow Village', desc: 'A military village covered in colourful paintings.' },
  'sml-bike': { name: 'Sun Moon Lake Bike Path', desc: 'Once named one of the world’s most beautiful cycling routes.' },
  'sml-boat': { name: 'Sun Moon Lake boat tour', desc: 'Hop between Shuishe, Xuanguang Temple and Ita Thao piers.' },
  formosan: { name: 'Formosan Aboriginal Culture Village', desc: 'Theme-park rides plus Indigenous culture shows.' },
  'ita-thao': { name: 'Ita Thao', desc: 'A Thao Indigenous village with snacks and handicrafts.' },
  wenhua: { name: 'Wenhua Road Night Market', desc: 'Chiayi’s liveliest street-food strip.' },
  hinoki: { name: 'Hinoki Village', desc: 'Japanese-era cypress-wood dormitories.' },
  'npm-south': { name: 'National Palace Museum Southern Branch', desc: 'A branch of the Palace Museum focused on Asian cultures.' },
  'alishan-forest': { name: 'Alishan Forest Recreation Area', desc: 'Giant-tree boardwalks, Sister Ponds and cherry blossoms in spring.' },
  zhushan: { name: 'Zhushan sunrise', desc: 'Take the early train up Zhushan for sunrise over the sea of clouds.', tip: 'Sunrise time changes daily; check the train time the night before.' },
  fenqihu: { name: 'Fenqihu Old Street', desc: 'A stop on the forest railway, famous for railway lunch boxes.' },
  chihkan: { name: 'Chihkan Tower', desc: 'Remains of the Dutch-era Fort Provintia.' },
  anping: { name: 'Anping Fort & Old Street', desc: 'Taiwan’s oldest fort and a snack-filled old street.' },
  shennong: { name: 'Shennong Street', desc: 'Old houses lit up at night, with small independent shops.' },
  chimei: { name: 'Chimei Museum', desc: 'Western art, musical instruments and arms in a palace-like building.' },
  sicao: { name: 'Sicao Green Tunnel', desc: 'A bamboo-raft ride through a mangrove tunnel.' },
  'garden-nm': { name: 'Tainan Garden Night Market', desc: 'Tainan’s biggest night market.', tip: 'Open only on Thursdays, Saturdays and Sundays.' },
  pier2: { name: 'Pier-2 Art Center', desc: 'Harbour warehouses turned art district.' },
  cijin: { name: 'Cijin Island', desc: 'Ferry over, ride a bike, eat seafood and watch the sunset.' },
  lotus: { name: 'Dragon & Tiger Pagodas (Lotus Pond)', desc: 'Enter through the dragon’s mouth and leave through the tiger’s for good luck.' },
  fgs: { name: 'Fo Guang Shan Buddha Museum', desc: 'A vast Buddhist cultural complex.' },
  ruifeng: { name: 'Ruifeng Night Market', desc: 'The locals’ favourite night market in Kaohsiung.' },
  formosa: { name: 'Formosa Boulevard Station (Dome of Light)', desc: 'Often listed among the world’s most beautiful metro stations.' },
  'kt-street': { name: 'Kenting Main Street', desc: 'Turns into a busy night market after dark.' },
  eluanbi: { name: 'Eluanbi Lighthouse', desc: 'The white lighthouse at Taiwan’s southern tip.' },
  nmmba: { name: 'National Museum of Marine Biology and Aquarium', desc: 'An undersea tunnel and beluga whales; a family favourite.' },
  longpan: { name: 'Longpan Park', desc: 'Coral-reef cliffs over the Pacific; good for stargazing.' },
  baisha: { name: 'Baisha Bay', desc: 'A white-sand beach for swimming.' },
  qixingtan: { name: 'Qixingtan Beach', desc: 'A crescent pebble bay; great at sunrise.' },
  dongdamen: { name: 'Dongdamen Night Market', desc: 'A large night market with an Indigenous food section.' },
  qingshui: { name: 'Qingshui Cliffs', desc: 'Kilometre-high cliffs dropping straight into the Pacific.', tip: 'Check whether the Suhua Highway and viewpoint are open before going.' },
  'taroko-np': { name: 'Taroko National Park (open sections)', desc: 'Gorges, tunnels and rivers in a dramatic marble landscape.', tip: 'Some trails and roads are still being repaired after earthquakes; check the national park notices before you go.' },
  mrbrown: { name: 'Mr. Brown Avenue (Chishang)', desc: 'Endless rice fields; best by bicycle.' },
  luye: { name: 'Luye Highland', desc: 'Home of the summer hot-air balloon festival.' },
  sanxiantai: { name: 'Sanxiantai', desc: 'An eight-arch footbridge over the sea; a sunrise spot.' },
  tiehua: { name: 'Tiehua Music Village', desc: 'Balloon lanterns and live music at night.' },
  zhiben: { name: 'Zhiben Hot Springs', desc: 'A well-known hot-spring area in the east.' },
  twinheart: { name: 'Twin Hearts Stone Weir (Qimei)', desc: 'A heart-shaped stone fish trap; take a boat to Qimei.' },
  bridge: { name: 'Penghu Great Bridge', desc: 'The sea bridge linking Baisha and Xiyu.' },
  jibei: { name: 'Jibei Sand Tail', desc: 'A white sandbar with water sports.' },
};

export const FOOD_EN = {
  'taipei:牛肉麵': { name: 'Beef noodle soup', desc: 'Braised or clear broth; Taipei’s signature dish.' },
  'taipei:小籠包': { name: 'Xiaolongbao (soup dumplings)', desc: 'Thin skins full of hot broth.' },
  'taipei:滷肉飯': { name: 'Braised pork rice', desc: 'Stewed minced pork over rice; cheap and classic.' },
  'taipei:士林夜市': { name: 'Shilin Night Market', desc: 'Taipei’s biggest night market: giant fried chicken, pan-fried buns, games.' },
  'taipei:饒河街觀光夜市': { name: 'Raohe Night Market', desc: 'Famous for the pepper buns at the entrance.' },
  'taipei:寧夏夜市': { name: 'Ningxia Night Market', desc: 'Traditional Taiwanese snacks: oyster omelette, taro balls.' },
  'taipei:珍珠奶茶': { name: 'Bubble tea', desc: 'Taiwan’s national drink; choose your sugar and ice level.' },
  'jiufen:芋圓': { name: 'Taro balls', desc: 'Chewy taro balls over shaved ice or in warm soup.' },
  'jiufen:草仔粿': { name: 'Herbal rice cake', desc: 'Mugwort dough filled with radish or red bean.' },
  'jiufen:魚丸湯': { name: 'Fish ball soup', desc: 'A common snack on the old street.' },
  'tamsui:阿給': { name: 'A-gei', desc: 'Fried tofu stuffed with glass noodles, sealed with fish paste, in sweet chilli sauce.' },
  'tamsui:鐵蛋': { name: 'Iron eggs', desc: 'Eggs braised and dried until dark and chewy.' },
  'tamsui:魚酥': { name: 'Fish crisps', desc: 'Crunchy fish-paste snacks.' },
  'pingxi:雞翅包飯': { name: 'Rice-stuffed chicken wing', desc: 'Deboned wings stuffed with fried rice and grilled.' },
  'pingxi:花生冰淇淋捲': { name: 'Peanut ice-cream roll', desc: 'Peanut brittle, ice cream and cilantro in a crepe.' },
  'keelung:鼎邊趖': { name: 'Ding bian cuo', desc: 'Rice-batter noodles in a thick seafood soup.' },
  'keelung:營養三明治': { name: '“Nutritious” sandwich', desc: 'A fried bun with egg, ham, tomato and mayo.' },
  'keelung:泡泡冰': { name: 'Paopao ice', desc: 'Hand-whipped, fluffy shaved ice.' },
  'yilan:三星蔥油餅': { name: 'Sanxing scallion pancake', desc: 'Crispy pancake packed with local scallions.' },
  'yilan:卜肉': { name: 'Bu rou', desc: 'Battered, deep-fried pork strips.' },
  'yilan:牛舌餅': { name: 'Ox-tongue biscuits', desc: 'Thin, crisp biscuits; Yilan’s classic souvenir.' },
  'taoyuan:大溪豆干': { name: 'Daxi braised tofu', desc: 'Firm tofu braised until savoury.' },
  'taoyuan:客家菜': { name: 'Hakka dishes', desc: 'Salty, fragrant Hakka home cooking.' },
  'hsinchu:新竹米粉': { name: 'Hsinchu rice noodles', desc: 'Thin, wind-dried rice noodles, fried or in soup.' },
  'hsinchu:貢丸湯': { name: 'Pork ball soup', desc: 'Bouncy pork meatballs, Hsinchu’s speciality.' },
  'hsinchu:客家粄條': { name: 'Hakka flat noodles', desc: 'Wide rice noodles from the Hakka hills.' },
  'taichung:太陽餅': { name: 'Sun cakes', desc: 'Flaky pastry with a malt-sugar filling; Taichung’s souvenir.' },
  'taichung:珍珠奶茶': { name: 'Bubble tea', desc: 'Taichung claims to be where bubble tea began.' },
  'taichung:大麵羹': { name: 'Da mian geng', desc: 'Thick alkaline noodles in broth; old-school Taichung.' },
  'taichung:一中街商圈': { name: 'Yizhong Street', desc: 'A student snack street with low prices.' },
  'sunmoonlake:日月潭紅茶(台茶18號)': { name: 'Sun Moon Lake black tea (Ruby No. 18)', desc: 'Black tea with natural notes of cinnamon and mint.' },
  'sunmoonlake:香菇茶葉蛋': { name: 'Mushroom tea eggs', desc: 'The famous tea eggs at Xuanguang Temple.' },
  'sunmoonlake:總統魚': { name: '“President fish”', desc: 'A local lake fish, usually steamed.' },
  'chiayi:火雞肉飯': { name: 'Turkey rice', desc: 'Chiayi’s signature: shredded turkey and savoury fat over rice.' },
  'chiayi:方塊酥': { name: 'Square puff biscuits', desc: 'Layered, crunchy biscuits; a classic souvenir.' },
  'alishan:奮起湖便當': { name: 'Fenqihu lunch box', desc: 'Old-style railway bento in a metal box.' },
  'alishan:阿里山高山茶': { name: 'Alishan high-mountain tea', desc: 'Delicate oolong grown at high altitude.' },
  'tainan:牛肉湯': { name: 'Beef soup', desc: 'Raw local beef cooked by pouring hot broth over it; a Tainan breakfast.' },
  'tainan:擔仔麵': { name: 'Danzai noodles', desc: 'A small bowl of noodles with minced pork and shrimp.' },
  'tainan:碗粿': { name: 'Wa-gui (rice pudding)', desc: 'Steamed savoury rice pudding with sauce.' },
  'tainan:鱔魚意麵': { name: 'Eel noodles', desc: 'Wok-fried eel with noodles, slightly sweet and sour.' },
  'tainan:蝦捲': { name: 'Shrimp rolls', desc: 'Crispy fried shrimp rolls from Anping.' },
  'kaohsiung:海鮮': { name: 'Seafood', desc: 'Fresh seafood cooked to order on Cijin.' },
  'kaohsiung:木瓜牛奶': { name: 'Papaya milk', desc: 'Kaohsiung’s classic drink.' },
  'kaohsiung:六合夜市': { name: 'Liuhe Night Market', desc: 'The night market most visitors know.' },
  'kenting:綠豆蒜': { name: 'Mung bean dessert', desc: 'Hengchun’s sweet soup of hulled mung beans.' },
  'kenting:洋蔥料理': { name: 'Onion dishes', desc: 'Hengchun onions are sweetest in spring.' },
  'kenting:海鮮': { name: 'Seafood', desc: 'Sashimi at Houbihu harbour is the freshest.' },
  'hualien:扁食': { name: 'Wontons', desc: 'Hualien-style wontons with thin skins.' },
  'hualien:炸彈蔥油餅': { name: '“Bomb” scallion pancake', desc: 'Deep-fried scallion pancake with a runny egg inside.' },
  'hualien:花蓮麻糬': { name: 'Hualien mochi', desc: 'Soft mochi in many flavours; the classic souvenir.' },
  'taitung:池上便當': { name: 'Chishang lunch box', desc: 'Bento showing off Chishang’s famous rice.' },
  'taitung:釋迦': { name: 'Sugar apple', desc: 'Taitung’s famous fruit, in season in autumn and winter.' },
  'taitung:原住民風味餐': { name: 'Indigenous cuisine', desc: 'Wild greens, bamboo-tube rice and mountain pork.' },
  'penghu:仙人掌冰': { name: 'Cactus-fruit ice', desc: 'Bright pink, sweet and sour ice.' },
  'penghu:黑糖糕': { name: 'Brown sugar cake', desc: 'Soft, springy cake; Penghu’s souvenir.' },
  'penghu:海鮮': { name: 'Seafood', desc: 'Squid, sea urchin and Penghu loofah.' },
};

export const SHOP_EN = {
  阜杭豆漿: { name: 'Fuhang Soy Milk', area: 'Huashan Market 2F · Shandao Temple MRT', note: 'Thick flatbread with egg and savoury soy milk; expect a 30+ minute queue in the morning.' },
  林東芳牛肉麵: { name: 'Lin Dong Fang Beef Noodles', area: 'Bade Road', note: 'Order half tendon, half beef and add their beef-fat chilli.' },
  永康牛肉麵: { name: 'Yong Kang Beef Noodles', area: 'Yongkang Street · Dongmen MRT', note: 'A long-running spicy braised beef noodle shop.' },
  '鼎泰豐 信義店': { name: 'Din Tai Fung (Xinyi Rd original)', area: 'Xinyi Road · Dongmen MRT', note: 'The original store of the soup-dumpling chain; take a queue number online.' },
  金峰滷肉飯: { name: 'Jin Feng Braised Pork Rice', area: 'Nanchang Road · CKS Memorial Hall MRT', note: 'Cheap and fast, with a queue that moves quickly.' },
  福州世祖胡椒餅: { name: 'Fuzhou Pepper Buns', area: 'Raohe Night Market entrance · Songshan MRT', note: 'Charcoal-oven pepper buns; wait for a fresh batch.' },
  阿柑姨芋圓: { name: 'A-Gan-Yi Taro Balls', area: 'Off Shuqi Road, Jiufen', note: 'Seats with mountain and sea views.' },
  賴阿婆芋圓: { name: 'Grandma Lai’s Taro Balls', area: 'Jishan Street, Jiufen', note: 'A long-running handmade taro ball shop.' },
  淡水文化阿給: { name: 'Tamsui Wenhua A-gei', area: 'Zhenli Street', note: 'One of the original a-gei shops.' },
  三協成: { name: 'San Xie Cheng Bakery', area: 'Zhongzheng Road, Tamsui', note: 'A century-old pastry shop.' },
  李鵠餅店: { name: 'Li Hu Bakery', area: 'Ren 3rd Road, near Miaokou', note: 'Century-old bakery: pineapple cakes and mung bean pastries.' },
  黃日香豆干: { name: 'Huang Ri Xiang Tofu', area: 'Heping Old Street, Daxi', note: 'The best-known Daxi braised tofu brand.' },
  '春水堂 四維創始店': { name: 'Chun Shui Tang (Siwei original)', area: 'Siwei Street', note: 'One of the tea houses credited with inventing bubble tea.' },
  宮原眼科: { name: 'Miyahara', area: 'Zhongshan Road, by Taichung Station', note: 'Ice cream and gift boxes in a beautiful old building.' },
  陳允寶泉: { name: 'Chen Yun Pao Chuan', area: 'Several stores in Taichung', note: 'A century-old sun cake maker.' },
  玄光寺阿婆茶葉蛋: { name: 'Grandma’s Tea Eggs at Xuanguang Temple', area: 'Xuanguang Temple pier', note: 'Grab some on your boat tour.' },
  噴水火雞肉飯: { name: 'Pen Shui Turkey Rice', area: 'Zhongzheng Road (fountain roundabout)', note: 'The most famous turkey rice shop.' },
  劉里長雞肉飯: { name: 'Liu Li Zhang Chicken Rice', area: 'Gongming Road', note: 'Where locals queue for turkey rice.' },
  阿堂鹹粥: { name: 'A-Tang Savoury Porridge', area: 'Ximen Road', note: 'Milkfish porridge from early morning until late morning.' },
  六千牛肉湯: { name: 'Liu Qian Beef Soup', area: 'Haian Road', note: 'Opens at dawn and closes when sold out.' },
  阿村第二代牛肉湯: { name: 'A-Cun Beef Soup', area: 'Baoan Road', note: 'Famous beef soup, open until about midday.' },
  富盛號碗粿: { name: 'Fu Sheng Hao Wa-gui', area: 'Ximen Road, near Chihkan Tower', note: 'A long-established rice pudding shop.' },
  '度小月擔仔麵 原始店': { name: 'Du Hsiao Yueh Danzai Noodles (original)', area: 'Zhongzheng Road', note: 'Where danzai noodles began.' },
  周氏蝦捲: { name: 'Chou’s Shrimp Rolls', area: 'Anping Road', note: 'Anping’s signature snack.' },
  興隆居: { name: 'Xing Long Ju', area: 'Liuhe 2nd Road', note: 'An old breakfast shop for soup buns and flatbread.' },
  港園牛肉麵: { name: 'Gang Yuan Beef Noodles', area: 'Dacheng Street, Yancheng', note: 'Famous for dry-mixed beef noodles.' },
  高雄婆婆冰: { name: 'Popo Ice', area: 'Qixian 3rd Road, Yancheng', note: 'An old fruit shaved-ice shop.' },
  阿伯綠豆饌: { name: 'A-Bo Mung Bean Dessert', area: 'Hengchun', note: 'A long-running mung bean dessert shop.' },
  戴記扁食: { name: 'Dai Ji Wontons', area: 'Zhonghua Road', note: 'One of Hualien’s signature wonton shops.' },
  液香扁食: { name: 'Yi Xiang Wontons', area: 'Xinyi Street', note: 'An old wonton shop with a clear, sweet broth.' },
  曾記麻糬: { name: 'Tseng Chi Mochi', area: 'Several stores in Hualien', note: 'The best-known mochi souvenir brand.' },
  悟饕池上飯包文化故事館: { name: 'Wu Tao Chishang Lunch Box Museum', area: 'Chishang', note: 'Lunch boxes plus a small rice-culture exhibit.' },
  全美行: { name: 'Chuan Mei Hang', area: 'Chishang', note: 'A long-established Chishang lunch box shop.' },
};

export const LINE_EN = {
  台灣高鐵: 'Taiwan High Speed Rail (HSR)',
  台鐵區間車: 'TRA local train',
  台鐵自強號: 'TRA Tze-Chiang express',
  '台鐵(瑞芳轉平溪線)': 'TRA via Ruifang + Pingxi line',
  台鐵南迴線: 'TRA South-Link line',
  '台鐵普悠瑪/太魯閣號': 'TRA Puyuma / Taroko express',
  '桃園機場捷運(直達車)': 'Taoyuan Airport MRT (express)',
  桃園機場捷運: 'Taoyuan Airport MRT',
  台北捷運淡水信義線: 'Taipei MRT Red Line (Tamsui-Xinyi)',
  '基隆客運 1062': 'Keelung Bus 1062',
  '基隆客運 788': 'Keelung Bus 788',
  '葛瑪蘭客運(國道5號)': 'Kamalan Bus (Freeway 5)',
  國道客運: 'Intercity bus',
  '南投客運 6670(高鐵台中站發車)': 'Nantou Bus 6670 (from HSR Taichung)',
  '台灣好行 7322 阿里山線': 'Taiwan Tourist Shuttle 7322 (Alishan)',
  '墾丁快線(高鐵左營站發車)': 'Kenting Express (from HSR Zuoying)',
  '台灣好行 太魯閣線': 'Taiwan Tourist Shuttle (Taroko)',
  '國內線班機(松山—馬公)': 'Domestic flight (Songshan–Magong)',
  '國內線班機(小港—馬公)': 'Domestic flight (Kaohsiung–Magong)',
  '布袋港—馬公 客輪': 'Ferry (Budai–Magong)',
};

export const TIP_EN = {
  '瑞芳站轉乘平溪線,可買平溪線一日週遊券。': 'Change to the Pingxi line at Ruifang; a Pingxi line day pass is available.',
  '東部幹線熱門,假日車票常需提前 28 天搶訂。': 'East-coast trains sell out; weekend tickets often need booking 28 days ahead.',
  'A18 高鐵桃園站可直接轉乘高鐵。': 'Change to the HSR at Airport MRT A18 (HSR Taoyuan).',
  '忠孝復興站 2 號出口附近搭車,假日排隊人潮多。': 'Board near Exit 2 of MRT Zhongxiao Fuxing; long queues on weekends.',
  '假日雪隧易塞車,時間可能加倍。': 'Weekend traffic in the Snow Mountain tunnel can double the time.',
  '也可搭阿里山林業鐵路,車票熱門需提早預訂。': 'You can also take the Alishan Forest Railway; book early, it sells out.',
  '部分路段可能因修復而管制,請先查詢公告。': 'Some sections may be closed for repairs; check notices first.',
  '時間含報到與機場接駁約 1 小時,飛行約 50 分鐘。': 'Includes about 1 hour for airport transfer and check-in; flight about 50 min.',
  '時間含報到與機場接駁約 1 小時,飛行約 40 分鐘。': 'Includes about 1 hour for airport transfer and check-in; flight about 40 min.',
  '含前往布袋港時間,航程約 90 分鐘;夏季航班較多,冬季東北季風常停航。': 'Includes getting to Budai port; about 90 min at sea. More sailings in summer; often cancelled in winter winds.',
};
